<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'ABS\\Tippgame\\Controller\\TournamentController' => $typo3InstallDir . 'typo3conf/ext/tippgame/Classes/Controller/TournamentController.php',
    'ABS\\Tippgame\\Domain\\Model\\Player' => $typo3InstallDir . 'typo3conf/ext/tippgame/Classes/Domain/Model/Player.php',
    'ABS\\Tippgame\\Domain\\Model\\Round' => $typo3InstallDir . 'typo3conf/ext/tippgame/Classes/Domain/Model/Round.php',
    'ABS\\Tippgame\\Domain\\Model\\Team' => $typo3InstallDir . 'typo3conf/ext/tippgame/Classes/Domain/Model/Team.php',
    'ABS\\Tippgame\\Domain\\Model\\Tournament' => $typo3InstallDir . 'typo3conf/ext/tippgame/Classes/Domain/Model/Tournament.php',
    'ABS\\Tippgame\\Domain\\Repository\\TournamentRepository' => $typo3InstallDir . 'typo3conf/ext/tippgame/Classes/Domain/Repository/TournamentRepository.php',
    'ABS\\Tippgame\\ViewHelpers\\MenuViewHelper' => $typo3InstallDir . 'typo3conf/ext/tippgame/Classes/ViewHelpers/MenuViewHelper.php',
);
